### ISSUE TITLE
Workshop is currently maintenance. error

### ISSUE THREAD

**Issue by eymndev** [ardatdev/artadosearch-source-v0.1#55]
When navigating to [artadosearch.com](https://artadosearch.com/), I encountered a problem while trying to access the Workshop section.

Steps to Reproduce:

	1.	Go to [artadosearch.com](https://artadosearch.com/).
	2.	Click on the Menu button.
	3.	Select Workshop from the dropdown.

Expected Behavior:
The Workshop page should load successfully, displaying the relevant content without any issues.

Actual Behavior:
An error occurred when attempting to access the Workshop page. (See attached screenshot: IMG_3962)

Screenshots:

![IMG_3962](https://github.com/user-attachments/assets/71350b03-95df-4477-97ec-5a973ce5acfb)
![IMG_3964](https://github.com/user-attachments/assets/83d095f9-2684-42c0-9167-c3646880b5d4)
]
![IMG_3966](https://github.com/user-attachments/assets/7f0424c0-613f-4c8d-a4ad-2f1bbf2be058)

Environment:

	•	Browser: [Safari

	•	Operating System: [iPadOS 18.1]

Additional Information:
Any other details that might help in diagnosing the issue.

translated by ChatGPT o1 mini Turkish -> English

**Comment by ardatdev** [comment]
It is under maintenance.
